controller_names:
  - left_tmr_arm_controller
  - right_tmr_arm_controller

left_tmr_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  state_publish_rate: 25
  action_monitor_rate: 10
  max_velocity: 5.0
  max_acceleration: 5.0
  default: true
  joints:
    - leftjoint_1
    - leftjoint_2
    - leftjoint_3
    - leftjoint_4
    - leftjoint_5
    - leftjoint_6

right_tmr_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - rightjoint_1
    - rightjoint_2
    - rightjoint_3
    - rightjoint_4
    - rightjoint_5
    - rightjoint_6
