left_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  max_velocity_scaling_factor: 2.0  # Ajuste este valor conforme necess치rio
  max_acceleration_scaling_factor: 2.0  # Ajuste este valor conforme necess치rio

right_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  max_velocity_scaling_factor: 1.0  # Ajuste este valor conforme necess치rio
  max_acceleration_scaling_factor: 1.0  # Ajuste este valor conforme necess치rio
