# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_controller
    - right_controller

  left_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - leftjoint_1
      - leftjoint_2
      - leftjoint_3
      - leftjoint_4
      - leftjoint_5
      - leftjoint_6
  right_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - rightjoint_1
      - rightjoint_2
      - rightjoint_3
      - rightjoint_4
      - rightjoint_5
      - rightjoint_6